### ISSUE TITLE
Gather Data

### ISSUE THREAD

**Issue by prezmora** [Big-Data-Capstone-S2024/WildFireSimulation#27]
Gather historical wildfire data, weather data, topographic data, and other relevant geospatial datasets.

Deliverables:
Gather Data here
[Canadian Forest Fire Weather Index (FWI) System - Web Service (WMS)](http://cwfis.cfs.nrcan.gc.ca/geoserver/ows?service=wms&version=1.3.0&request=GetCapabilities) (WMS)

[Canadian Forest Fire Behavior Prediction (FBP) System - Web Map Service (WMS)](https://cwfis.cfs.nrcan.gc.ca/geoserver/ows?service=wms&version=1.3.0&request=GetCapabilities)

**Comment by ancarlosmendes** [comment]
The notebook code has been adjusted after reviewing the comments
